# Generated by Django 4.2.20 on 2025-04-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('tone', models.CharField(max_length=50)),
                ('scope', models.CharField(max_length=50)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csvs/')),
                ('include_hashtags', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
